### ISSUE TITLE
m1pro电脑运行报错，不知道什么原因

### ISSUE THREAD

**Issue by ccqiuqiu** [ArcSurge/Termius-Pro-zh_CN#2]
❯ python lang.py
Traceback (most recent call last):
File "/Applications/Termius.app/Contents/Resources/lang.py", line 169, in
main()
File "/Applications/Termius.app/Contents/Resources/lang.py", line 149, in main
termius_path = os.path.join(os.getenv('USERPROFILE'), 'AppData', 'Local', 'Programs', 'Termius', 'resources')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ccqiuqiu** [comment]
我修改了一下169行，重新执行就成功了
   
 # termius_path = os.path.join(os.getenv('USERPROFILE'), 'AppData', 'Local', 'Programs', 'Termius', 'resources')
    termius_path = '/Applications/Termius.app/Contents/Resources/'

**Comment by ArcSurge** [comment]
这个脚本没适配macos
